"""Planning agent for expanding research ideas into detailed execution plans."""

from typing import Dict, Any
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain.schema import HumanMessage, AIMessage, SystemMessage
from src.agents.base import BaseAgent
from src.state.agent_state import AgentState
from config.settings import settings
import json


class PlanningAgent(BaseAgent):
    """PLACEHOLDER: Agent that transforms rough ideas into detailed execution plans.
    
    This agent focuses purely on plan decomposition without knowledge of specific 
    tools or agents. It breaks down research objectives into logical steps with 
    dependencies and success criteria, leaving the orchestrator to map these 
    abstract plans to concrete resources.
    
    Note: This is currently a placeholder. Full implementation exists elsewhere
    and will be integrated when ready.
    """
    
    def __init__(self, llm: ChatGoogleGenerativeAI = None):
        super().__init__(
            name="planning",
            mcp_tools=[],  # Planning agent doesn't use tools directly
            description="Transforms research ideas into detailed, structured execution plans"
        )
        self.llm = llm or ChatGoogleGenerativeAI(
            model=settings.orchestrator_model,
            temperature=0,
            max_tokens=None,
            timeout=None,
            max_retries=2,
            google_api_key=settings.google_api_key
        )
    
    async def process(self, state: AgentState) -> AgentState:
        """PLACEHOLDER: Create a structured plan from a research idea."""
        
        current_task = state.get("current_task", "")
        
        # Log start of planning
        self.log_message(state, f"Creating execution plan for: {current_task}")
        
        # Single LLM call to determine both: sufficient info + fast track eligibility
        decision = await self._analyze_task_requirements(current_task)
        
        if not decision["has_sufficient_info"]:
            # Need more info - set fast track if applicable
            if decision["should_fast_track"]:
                state["fast_track"] = "planning"
            
            # Request more information
            clarification_msg = decision["clarification_message"]
            state["messages"].append(AIMessage(content=clarification_msg))
            state["next_agent"] = None
            self.log_message(state, "Requested more planning parameters from user")
            return state
        
        # We have sufficient parameters - proceed with planning
        # PLACEHOLDER: Simple plan structure
        # In the full implementation, this would use sophisticated prompting
        # to break down research objectives into detailed steps
        placeholder_plan = {
            "research_objective": current_task,
            "plan_steps": [
                {
                    "step_id": 1,
                    "description": "Gather relevant data sources",
                    "type": "data_collection",
                    "success_criteria": "Data successfully acquired and validated",
                    "dependencies": []
                },
                {
                    "step_id": 2, 
                    "description": "Perform initial analysis",
                    "type": "analysis",
                    "success_criteria": "Analysis results generated and verified",
                    "dependencies": [1]
                },
                {
                    "step_id": 3,
                    "description": "Review relevant literature",
                    "type": "literature_review", 
                    "success_criteria": "Context established from existing research",
                    "dependencies": []
                },
                {
                    "step_id": 4,
                    "description": "Synthesize findings",
                    "type": "synthesis",
                    "success_criteria": "Research conclusions formulated",
                    "dependencies": [1, 2, 3]
                }
            ],
            "estimated_complexity": "medium",
            "planning_notes": f"Generated by placeholder planning agent for: {current_task}"
        }
        
        # Store the plan in state
        state["task_breakdown"] = placeholder_plan["plan_steps"]
        state["metadata"]["research_plan"] = placeholder_plan
        state["metadata"]["planning_complete"] = True
        
        # Inform user about the plan
        plan_summary = f"Created execution plan with {len(placeholder_plan['plan_steps'])} steps:\n"
        for step in placeholder_plan["plan_steps"]:
            plan_summary += f"- Step {step['step_id']}: {step['description']} ({step['type']})\n"
        
        plan_summary += f"\nPlan created for: {current_task}"
        plan_summary += "\nNote: This is a placeholder plan. Full planning implementation will be integrated later."
        
        state["messages"].append(AIMessage(content=plan_summary))
        self.log_message(state, "Planning complete - returning to orchestrator for execution mapping")
        
        # Return to orchestrator to map plan to specific agents
        state["next_agent"] = "orchestrator"
        
        return state
    
    async def _analyze_task_requirements(self, task: str) -> dict:
        """Single LLM call to analyze task and determine next steps."""
        prompt = f"""
        Analyze this planning task: "{task}"
        
        Determine:
        1. Do I have sufficient information to create a meaningful research plan?
        2. If not, is this a straightforward planning request that should fast-track back to me?
        
        For sufficient information, I need: clear research objective, scope, goals, or specific questions to address.
        
        Fast track if:
        - This is clearly a planning request, just missing specific details
        - User will likely provide specifics and want planning to proceed
        
        Don't fast track if:
        - Request is ambiguous about what type of work to do
        - User might want to change direction entirely
        - Unclear if they want planning vs data gathering vs analysis vs simulation
        
        Return JSON:
        {{
            "has_sufficient_info": true/false,
            "should_fast_track": true/false,
            "clarification_message": "specific message if more info needed"
        }}
        """
        
        response = await self.llm.ainvoke([HumanMessage(content=prompt)])
        
        try:
            # Strip markdown code block formatting if present
            content = response.content.strip()
            if content.startswith("```json"):
                content = content[7:]
            if content.startswith("```"):
                content = content[3:]
            if content.endswith("```"):
                content = content[:-3]
            content = content.strip()
            
            result = json.loads(content)
            return result
        except:
            # Fallback if JSON parsing fails
            return {
                "has_sufficient_info": False,
                "should_fast_track": False,
                "clarification_message": "I need more specific information about what to plan. Please specify: research objective, scope, goals, or specific questions to address."
            } 